### ISSUE TITLE
function getNextModelId() function will cause issues

### ISSUE THREAD

**Issue by Towerful** [sbarre/eloquent-versioned#17]
so,  
current version ( 0.0.7 )  
in the Trait ~line 183 ( https://github.com/sbarre/eloquent-versioned/blob/5cccfa9f29a230945697fd290a66c197bb659e7f/src/Traits/Versioned.php#L255 )

you are getting the Max of the ID column.  
What happens if a record is inserted elsewhere between the call and the return of this function (and final saving of this model)?  
The model_id will reference the wrong record.  
Or, if the latest model (eg `id: 177`, previous model being `id: 176`) has been deleted at some point, return will be `177`, but MySQL autoinc will set the model `id:178`

Would it not be better to save first, then self-reference the new model & update? at the expense of an extra DB query.. 
I would love to set up a pull-request, but I have no idea how!

**Comment by EspadaV8** [comment]
One solution would be to default to using the records primary key for the `model_id` when saving. My prefered method though would be to use UUIDs for the `model_id` since they are guaranteed to be unique and not cause issues (and can be created without needing to do a database query).

**Comment by Towerful** [comment]
Makes sense. 
But forgive me if I don't understand this. Would this not slow down retrieving older versions (I thought foreign keys had to be primary keys).  
With the recent changes of the way versioning is handled (ie recent record is the most recent version), this is less of an issue. And perhaps it should just be taken as a performance hit for versioning model records in such a transparent way...

**Comment by EspadaV8** [comment]
Yes, foreign keys do need to be a primary key (or at least a unique key).

I'm not sure what you mean about it slowing things down though. With the current set up it's not possible to have foreign keys pointing to the latest version of a record without a fair bit of work being done after every save to update the foreign keys to point to the new `p_key` values.

There is a PR open that I'm working on that will flip the way versions are saved though so that the original `p_key` is always used by the latest version of the record. When saves are made the current, pre-edited row is duplicated and inserted with a new `p_key` and then the original record with it's existing `p_key` is saved as normal. This would allow foreign keys to point to the latest version of the record.

However, I've not been able to fully test things out yet (although feel free to check out #16 to see how it works and/or give it a test).

**Comment by Towerful** [comment]
actually, I see this has pretty much been described in issue #8 but at a tag of a tangent.  
I think a UUID column that is generated on insert, and shared on update would be a solution to both a potential race condition (is that the right term?) and models not using auto-inc ID

**Comment by Towerful** [comment]
Yes, I've seen that. sorry, I didn't realize that hadn't been merged.  
This issue has also been discussed in issue #8 , altho tangentially.

**Comment by EspadaV8** [comment]
No worries. I'm currently working on another package at the moment, but that PR is in a mostly finished state. The few remaining things I'd like to do are really just some clean ups and then to make it the default behaviour.

After that I was planning on switching the `model_id` to a UUID so that it doesn't need to hit the DB to get the next one (since with that PR the `model_id` is only used internally there's no need to make it look like a normal autoincrementing column).

**Comment by Towerful** [comment]
I won't lie. I'm quite excited for these PRs to be merged into the master branch!  
Keep up the good work! :)
